import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
p.on('console', m => { if (m.type() === 'error') console.log('CE:', m.text().slice(0, 150)); });
const ts = Date.now();
const email = 'qa.prod.' + ts + '@exemple.ne';
await p.goto('https://boutique-client-two.vercel.app/inscription', { waitUntil: 'networkidle' });
await p.locator('input[name=full_name]').fill('QA Prod');
await p.locator('input[name=email]').fill(email);
await p.locator('input[name=phone]').fill('9' + String(ts).slice(-7));
await p.locator('input[name=password]').first().fill('Test12345');
await p.locator('input[name=confirm_password]').fill('Test12345');
await p.locator('input[type=checkbox]').check().catch(() => {});
await p.locator('button[type=submit]').first().click();
await p.waitForTimeout(7000);
console.log('URL:', p.url());
const t = (await p.locator('body').innerText()).slice(0, 300);
console.log(t);
await b.close();
